# Generated by Django 4.0.4 on 2022-05-12 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('googleId', models.CharField(max_length=30)),
                ('imageUrl', models.URLField()),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('givenName', models.CharField(max_length=60)),
                ('familyName', models.CharField(max_length=60)),
            ],
        ),
    ]
